### ISSUE TITLE
few bugs.

### ISSUE THREAD

**Issue by El3ctricFX** [akopachov/sveltab#18] opened 2024-12-09 01:41 UTC
## Bugs / Issues (not real big but just things i noticed)

just a few things i noticed when first using it.

- whenever i go to add a new widget it'll open the dropdown but when i go to close it (which i assume would happen when clicking on it again right it doesnt)

- when ever clicking around ill find like empty widgets for ex in this screenshot i clicked above and i found some random widget (its the clock widget that doesnt appear for some reason) thats just empty (and i cant delete it)

![image](https://github.com/user-attachments/assets/6019054f-103a-4f8b-b09e-d0e5ae8807ea)

- Also when ever re adjusting the screen size the widgets aren't aligned
     - and when adjusting the browser the screen shakes and you can see the size adjusting

## Suggestions

- would you be able to make a daily bible verse widget of some kind?

- For the links portion would you be able to make it so that instead of just having a portrait mode to where text is just bellow it, would you be able to add like a landscape option to where its beside the logo?

- would you be able to make it so that theres a grid like option to make it more locked in like momentum or even tabliss?

## Good job on the project

Also just overall great job on the project i really like how you added the filter option and just everything about the tab addon, Great job

**Comment by akopachov** [comment] 2024-12-09 12:11
Thank you for your report and all the suggestions. Appreciate it.

Could you please additionally provide information about the browser you are using?

It is pretty weird that pretty simple "Clock" widget is not rendered for you. Are there any exception details logged in the console?

**Comment by El3ctricFX** [comment] 2024-12-10 00:10
in that screenshot im using [Mullvad](https://mullvad.net/en/browser)

and where can i find such logs?

**Comment by El3ctricFX** [comment] 2024-12-10 00:11
also considering i just found this,

i was going to try backing it up and using it on brave with the configuration i have but it will not backup (restore button works but not backup)

**Comment by El3ctricFX** [comment] 2024-12-10 00:15
Things found as of now when testing with brave

## Issues 

- Still cant use drop downs

## Things that dont work on mullvad but do work does work on brave

- i can click on backup and it will show up
- i can see the clock widget

**Comment by akopachov** [comment] 2024-12-10 11:05
It looks like Mullvad browser doesn't support [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) API, which is used by Sveltab for "Clock" and "Date" widgets, and that is why they are not getting rendered for you. I'm going to put some code to let them render some placeholder like "Unsupported" or so.

**Comment by akopachov** [comment] 2024-12-10 11:25
Actually, found a better workaround. If [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) is not supported, then it will use another way (that is slower a bit, but at least it is working even without OffscreenCanvas).

Pushed this and other fixes to [demo website](https://demo.sveltab.com/) feel free to give it a try there until I publish new version to the stores

**Comment by El3ctricFX** [comment] 2024-12-10 21:03
just checked it out and seems that mostly everything is fixed, the drop down and i can see the clock now.

but idk if you saw this when i'm mentioned it but on mulllvad i cant actually use the backup button for whatever reason.

also for whenever changing colors of links i can no longer change it to plain white on both brave and mullvad

![image](https://github.com/user-attachments/assets/6c23bcb1-90d6-45ab-b810-ce4f8b278fc8)

also for the suggestions listed above are you able to still implement those like the grid type option?

overall good job on the fixes!

**Comment by akopachov** [comment] 2024-12-11 08:22
Hey, just created another issue to track the "Daily Bible verse" widget you suggested.

Also, I just checked again on the Mullvad browser and both, Backup and Color picker functionality seems to be working as expected (see video attached). Could you please check if you have some specific browser extension or settings that may lead to the behavior you described?

https://github.com/user-attachments/assets/1bfe9c10-812a-4a09-ad99-468f9deb6a5a

**Comment by El3ctricFX** [comment] 2024-12-11 23:16
for the snappable grid it wasn't exactly what i meant (still great addition though, may i add) 

i meant to say almost a locked in environment to where we can just add a widget and it forms a template (kinda like in tabliss how instead of moving stuff with our cursor it stays in place cause whenever i go from full screen to not full screen for ex the widgets (like links) get off centered (like the search bar will stay in the middle but then say i put links bellow it directly, it will be on the other side of the screen) so maybe implementing a group option would help? (assuming the snappable grid option in settings is what you added)

also as for the issues. it was dark reader that had removed white (i just didnt notice considering previously sveltab was the default homepage but when i looked it was on the demo so my bad)

but as for backup i disabled all my extensions expect (mullvad browser extension, noscript, & ublock orgin) which all in mullvad by default so idk why it ain't working for me. (i even tried "trusting" the demo website in noscript but nothing.) also i will note this incase its relevant i use the linux version of mullvad while noticing your on windows with explorer. (i doubt it matters but idk) 

also just to note the backup option works perfectly fine for me in brave just in mullvad which is weird.

**Comment by akopachov** [comment] 2024-12-12 08:56
ah, I see.

What you described as a template was actually exact reason why I started SvelTab :) I felt too limited with Tabliss pre-defined template, not being able to precisely put widgets to where I want them to be.

Instead, in Sveltab I built a way more flexible approach to define how widgets should behave on browser resize (at least I think so)

Each widget, among others, has the following options:

![image](https://github.com/user-attachments/assets/b6a18285-e6eb-44e7-b32f-18a3218aed89)

"Anchor" - defines the relative anchor for the widget. By default, it is top-left corner, and if you resize the browser window, then the widget will stay as is to where it is. However, if you set it to bottom-right, then the widget will stay in the same position, but relative to bottom-right corner. Same for the rest of the directions.

"Position" - defines how the widget's relative position should be affected by browser window resize. "Fixed" - means that it should not change, "Scale" - means that the position should relatively scale the same way how you resize the browser window.

"Size" - defines how the widget's size should be affected by browser window resize. "Fixed" - means that it should not change, "Scale" - means that the size of a widget should relatively scale the same way how you resize the browser window.

See the attached video for a visual explanation

https://github.com/user-attachments/assets/67291be4-f903-455c-b459-bec31ae80839

I know I should do a better job explaining this feature, as it is not described anywhere. Like a set of youtube videos or so.

**Comment by akopachov** [comment] 2024-12-12 09:14
Also, I am glad we found the cause of the corrupted color picker. Going to put a small change into the code according to Dark Reader's [doc](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#disabling-dark-reader-on-your-site), to prevent it be applied to Sveltab.

As to the backup problem in Mullvad, can you check the browser's console if there are any logged errors there? You can open that console in Firefox\Mullvad hamburger menu

![image](https://github.com/user-attachments/assets/05911b96-00da-4814-b484-6d5aa82f277b)

**Comment by El3ctricFX** [comment] 2024-12-12 22:22
here's what i got from the console if that means anything
![image](https://github.com/user-attachments/assets/5b13d226-b05e-44f6-887a-15cd874b76bf)
when going to the demo website

and then when i click backup i get the following error
![image](https://github.com/user-attachments/assets/67b1c45b-5385-4368-92d8-9ffd17388d55)

**Comment by El3ctricFX** [comment] 2024-12-12 22:43
also just another thing i believe you should add. 

# Suggestion

- add Luminosity (darker or brighter) slider for the wallpaper
 
 considering you have the filters there cool and all but sometimes they can be super bright and making it so we can't even see our widgets

could even add like a filter adjuster or controller or something of the sort

<hr>

also just want to say good job with all the implementations you had made up to this point, and even just overall great job with the project!

**Comment by El3ctricFX** [comment] 2024-12-17 00:09
> here's what i got from the console if that means anything ![image](https://private-user-images.githubusercontent.com/173574107/395346247-5b13d226-b05e-44f6-887a-15cd874b76bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTQ0MTYsIm5iZiI6MTczNDM5NDExNiwicGF0aCI6Ii8xNzM1NzQxMDcvMzk1MzQ2MjQ3LTViMTNkMjI2LWIwNWUtNDRmNi04ODdhLTE1Y2Q4NzRiNzZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMDA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODIwNTc4MGFkNTIyM2YzYzMzNDY4ODIzMDVhNWQyNWNkODYwZTAxODVmNmM4YTkyY2RjNzg0YWFlOGMxNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gQY9u-xihjAT0EKF9Id_zxS_E93qCqRJ50tQ1uMpkKg) when going to the demo website
> 
> and then when i click backup i get the following error ![image](https://private-user-images.githubusercontent.com/173574107/395346531-67b1c45b-5385-4368-92d8-9ffd17388d55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTQ0MTYsIm5iZiI6MTczNDM5NDExNiwicGF0aCI6Ii8xNzM1NzQxMDcvMzk1MzQ2NTMxLTY3YjFjNDViLTUzODUtNDM2OC05MmQ4LTlmZmQxNzM4OGQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMDA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWRjY2MxNGYwOWRmNjVlM2Q4NTk2MTZlYzE0ZDRmMmIwNmUzNDJkNjQ5ODcyNTc1MjdhZGM0YWJlMzU2OWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.odY3Dpa72XEEUcmjoUOJkNAk-bVrL3weo5VXIZlwVuM)

incase you didn't noticed i replied, heres the log

**Comment by akopachov** [comment] 2024-12-17 07:58
Yeah, I noticed it. Just took me a time to back to it, as I had to fix #21 first. Thank you!

Thanks to your logs, I narrowed down the root cause to [this](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/getDirectory#exceptions):

![image](https://github.com/user-attachments/assets/81e1e96b-a072-474c-ba8b-ab285a826ca1)

The only thing is that it is hard to say why in your case Mullvad was not able to map the requested directory to the local OPFS :)

**Comment by El3ctricFX** [comment] 2024-12-17 23:38
all good, just thought id mention it incase you hadn't seen it.

for some reason though, mullvad still isnt working for backups

![image](https://github.com/user-attachments/assets/47107f49-b19b-4631-b554-f3c25ff21dec)

**Comment by akopachov** [comment] 2024-12-18 09:42
hmmm..., could you please also share the OS you are using?

**Comment by El3ctricFX** [comment] 2024-12-18 13:56
> hmmm..., could you please also share the OS you are using?

Arch Linux with hyprland

**Comment by akopachov** [comment] 2024-12-19 08:00
Ah, finally managed to reproduce it, by installing VirtualBox + Arch + Mullvad there :)

So looks like Mullvad on Arch (not sure about other Linux distros, it it works just fine on Windows), the following line throws an exception:

```javascript
await navigator.storage.getDirectory()
```

Even though it should work just fine, given that `await navigator.storage.estimate()` shows that there is an available quota.

Sounds like a bug in Mullvad, tbh, but in any case, I'm going to put few checks to the code to avoid using OPFS if `await navigator.storage.getDirectory()` is not working.

**Comment by akopachov** [comment] 2024-12-19 08:56
Should be fixed in the latest build on [demo website](https://demo.sveltab.com/)

**Comment by El3ctricFX** [comment] 2024-12-20 02:38
Appreciate the fix. works all good now.

also just a question while this is still going on.

did you see my newer suggestions a little above before i sent the latest logs?

this is the main one im worried about.

> - add Luminosity (darker or brighter) slider for the wallpaper
>
> considering you have the filters there cool and all but sometimes they can be super bright and making it so we can't even see our widgets
>
> considering you have the filters there cool and all but sometimes they can be super bright and making it so we can't even see our widgets

**Comment by akopachov** [comment] 2024-12-20 08:16
Glad backup\restore started working just fine for you.

And yeah, that your suggestion is in my todo list, just postponed it for a bit as backup\restore issue was more important.

Nevertheless, I extracted this feature request into own issue #22, to keep track of all the progress on it there

**Comment by El3ctricFX** [comment] 2024-12-20 22:32
Thanks!
<hr>

Besides the quote suggestion i had also mentioned above, i believe that's it for now.

Great job on the project and how you implemented the suggestions!

**Comment by akopachov** [comment] 2024-12-21 06:01
Glad you like it! Feel free to open new issues with bugs, suggestions, ideas.

**Closed by akopachov** 2024-12-21 06:01 UTC
Labels: enhancement
